# Generated by Django 3.2.10 on 2021-12-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ('created_at',)},
        ),
    ]
